### ISSUE TITLE
Set Object ACL on existing file replaces it with an empty file

### ISSUE THREAD

**Issue by Kayrnt** [jamhall/s3rver#34] opened 2016-03-16 17:29 UTC
When using `setObjectAcl(awsBucket, awsKey, CannedAccessControlList.AuthenticatedRead)` over an existing uploaded file on s3rver, it shows following logs:

```
info: Stored object "myAwsKey" in bucket "myAwsBucket" successfully
info: PUT /myAwsBucket/myAwsKey?acl 200 - - 6.578 ms
```

Then downloading from  `http://localhost:4568/myAwsBucket/myAwsKey` serves file is an empty file just like the ACL change resulted in an upload of an empty file on that key.

**Comment by leontastic** [comment] 2018-01-18 15:37
@Kayrnt (or anyone else) If you are still having this issue can you please provide a minimal reproducible example?

**Comment by Kayrnt** [comment] 2018-01-18 16:08
Hi @leontastic, the issue is so "old" that I barely found any reference in my code especially since I used it in a project that is now deprecated. It was just done for continuous integration of my feature and I just didn't test it in the end.
Basically what I was doing is (in Scala)
```
val out: ByteArrayOutputStream = ...
val arr = out.toByteArray
val inputStream  = new ByteArrayInputStream(arr)
val client = new AmazonS3Client(awsCredential)
val metaData   = new ObjectMetadata
metaData.setContentLength(arr.length)
client.putObject(bucket, pathToFile, inputStream, metaData)
client.setObjectAcl(bucket, pathToFile, CannedAccessControlList.AuthenticatedRead)
client.getResourceUrl(bucket, pathToFile)
```

That I returned in http to my client that would then GET on that URL to compare the result with the expected one.

**Comment by leontastic** [comment] 2018-09-12 22:35
Closing due to staleness, if someone else encounters this I can reopen

**Closed by leontastic** 2018-09-12 22:35 UTC
Labels: bug
